### ISSUE TITLE
App rejected by iTunes Connect

### ISSUE THREAD

**Issue by ploddi** [spotxmobile/spotx-sdk-ios#4]
```Missing load commands - The executable at '/Payload/AppodealSandbox.app/AdManagerAssets.bundle/AdManagerAssets' does not have the necessary load commands. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider.```

**Comment by lcniles** [comment]
Thanks for the report; we're looking into this. Can you provide which version of Xcode you're using and which version of iOS you are targeting?

**Comment by dmitruss** [comment]
ios 9.1
XCode 7.1

**Comment by lcniles** [comment]
Thanks! Xcode 7.1 Beta or GA?

**Comment by dmitruss** [comment]
RELEASE VERSION

**Comment by lcniles** [comment]
Are you able to recreate this with SDK v2.1.1?

**Comment by dmitruss** [comment]
version 2.1.1 has same problem.

**Comment by lcniles** [comment]
I am curious what your linker command line looks like. Can you attach all of the build output?

**Comment by scottjulian** [comment]
Has this been resolved @dmitruss ?

**Comment by dmitruss** [comment]
i dont know, because we start use VPAID integration directrly

**Comment by lcniles** [comment]
@dmitruss - I'm closing this issue as it appears you have taken an alternate approach. Feel free to re-open with some more information if this is not the case.

Thanks!

**Comment by lcniles** [comment]
Update: With some help from Apple's Technical Support we uncovered the root cause here. The fix will be available as of v2.3 of our SDK.

Cheers!
