### ISSUE TITLE
 built for newer iOS version (9.1) than being linked (8.4)

### ISSUE THREAD

**Issue by dmitruss** [spotxmobile/spotx-sdk-ios#5]
There are many warnings when i compile app under ios 8.4 (or 7.1)
 
(null): Object file (/Users/dmitruss/Projects/Appodeal/AppodealSDK-iOS/Pods/SpotX-SDK/AdManager.framework/AdManager(SPXMraid_CreateCalendarEvent.o)) was built for newer iOS version (9.1) than being linked (8.4)

**Comment by lcniles** [comment]
The warnings are related to a new load command (LC_VERSION_MIN_IPHONEOS) introduced by the Xcode 7 linker. Our last patch release was compiled with Xcode 7; this load command appears to have been defaulted to iOS 9.1.

LC_VERSION_MIN_IPHONEOS will be set to 7.0 for the 2.1 release scheduled for 23 Nov. Is it acceptable to ignore this specific error in the meantime?

**Comment by dmitruss** [comment]
do you have new version?
